name: Build & Push Base image
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Base image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "hanschrome" --password-stdin
          docker build -f .docker/images/php-fpm/base/Dockerfile -t hanschrome/cmp-php-fpm-base:latest .
          docker push hanschrome/cmp-php-fpm-base:latest
