name: Build & Push Testing
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          docker run -it hanschrome/cmp-php-fpm-test:latest
